
\copy operadoras_saude FROM 'task3e4/files/operadoras.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/1T2023.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/1T2024.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/1T2023.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/2T2024.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/3T2023.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/3T2024.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/4T2023.csv' DELIMITER ';' CSV HEADER;

\copy demonstracoes_contabeis(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, VL_SALDO_INICIAL, VL_SALDO_FINAL) FROM 'task3e4/files/4T2024.csv' DELIMITER ';' CSV HEADER;

